package com.cognitiveclouds.socialite.utils;

public enum SocialRequestCodes {
	
	FACEBOOK_AUTH_REQUESTCODE,
	FACEBOOK_POST_REQUESTCODE,
	FACEBOOK_LOGOUT_REQUESTCODE,
	TWITTER_AUTH_REQUESTCODE,
	TWITTER_POST_REQUESTCODE,
	TWITTER_LOGOUT_REQUESTCODE
	
}
